# -*- coding: utf-8 -*-
"""soal_3_urai_rajut.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ypmgH98DX_5XgnoGI6L5zaAewCS_aS5n
"""

def urai(kata):                       # definisi fungsi dengan 1 parameter 'kata'
  '''
  Mengurai string.
  
  Misal, dari 'Github'
  menjadi 'GGiGitGithGithuGithub'

  Menggunakan pola iterasi NESTED LOOP.
  '''
  temp = ''                           # assign variable 'temp' berisi empty string untuk pengumpulan karakter nanti
  for i in range(len(kata)):          # masuk iterasi FOR LOOP dimulai dari 0 hingga angka yg didapat dari jumlah karakter 'kata'. variabel iterasi menggunakan 'i'
    for karakter in range(0, i+1):    # masuk iterasi NESTED FOR LOOP dimulai dari 0 hingga 'i' ditambah 1. variabel iterasi menggunakan 'karakter' untuk digunakan sebagai indexing
      temp += kata[karakter]          # dengan menggunakan indexing pada 'kata' dgn nilai index 'karakter', karakter tersebut ditambahkan ke 'temp'.
  return temp                         # hingga proses penambahan karakter selesai, return string baru pada 'temp'.

print(urai('Python'))
print(urai('Code'))
print(urai('Purwadhika'))

def rajut(kata):                                                                # definisi fungsi dengan 1 parameter 'kata'
  '''
  Merajut string yang telah terurai menggunakan fungsi rajut() .

  Misalnya, dari 'GGiGitGithGithuGithub'
  menjadi 'Github'
  '''

  temp = ''                                                                     # assign variabel 'temp' berisikan empty list

  for i in range(1):                                                            # masuk iterasi FOR LOOP sebanyak 1 baris
    for j in range(len(kata)-1, i,-1):                                          # masuk iterasi NESTED FOR LOOP secara mundur, karena kita tahu bahwa kata sesungguhnya ada di belakang. iterasi dimulai dari angka terbesar hingga terkecil, guna indexing kemudian
      temp += kata[j]                                                           # dengan menggunakan indexing sesuai angka NESTED FOR LOOP dari belakang karakter, dimasukkan ke 'temp'.
      if kata[j] in temp and kata[j] in kata.upper():                           # masuk ke kondisi JIKA karakter sudah ada di dalam 'temp' DAN karakternya berkapital, iterasi dihentikan. Karena kita tahu satu kata yang mau diambil berawalan kapital, maka ketika bertemu dengan huruf kapital berarti pencarian kata yang dimaksud sudah selesai.
        break
  return temp[::-1]                                                             # setelah iterasi selesai, reverse karakter menggunakan indexing

print(rajut('PPuPurPurwPurwaPurwadPurwadhPurwadhiPurwadhikPurwadhika'))
print(rajut('PPyPytPythPythoPython'))
print(rajut('CCoCodCode'))